### ISSUE TITLE
CSS常见技巧总结

### ISSUE THREAD

**Issue by AshoneA** [AshoneA/shone#5]
## 左边栏固定宽度：右边内容随屏幕变化
```CSS
nav {
  float: left;
  width: 25%;
}
section {
  margin-left: 25%;
}
```
